# Generated by Django 5.0.7 on 2024-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjects",
            options={"verbose_name_plural": "subjects"},
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
