# Generated by Django 5.0.7 on 2024-10-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0003_alter_student_email_subject_delete_subjects"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name_plural": "subjects"},
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="name",
            new_name="subject",
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learn.student"
            ),
        ),
    ]
