# Generated by Django 5.0.7 on 2024-10-30 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0005_subjectcontent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_pictures"
                    ),
                ),
                ("grade_level", models.CharField(max_length=50)),
                ("quiz_count", models.IntegerField(default=0)),
                ("last_subject_accessed", models.CharField(blank=True, max_length=100)),
                (
                    "ai_voice",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("female", "Female"),
                            ("male", "Male"),
                        ],
                        default="default",
                        max_length=10,
                    ),
                ),
                (
                    "completed_subjects",
                    models.ManyToManyField(blank=True, to="learn.subject"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bookmarked_tutorials",
                    models.ManyToManyField(blank=True, to="learn.tutorial"),
                ),
            ],
        ),
    ]
